name: PrisonEnchantCustom
main: com.stp.core.PrisonEnchantCustom
version: 1.0.1
commands:
  token:
    description: Main Command
    usage: /token
    permission: stp.token
  givepickaxe:
    description: Command for create User's Pickaxe.
    usage: /givepickaxe
    permission: stp.givepickaxe
  enchantsreload:
    description: Reload .yml.
    usage: /enchantsreload
    permission: stp.reload
  openenchantgui:
    description: Open Enchant GUI.
    usage: /openenchantgui
    permission: stp.openenchantgui
