# Configuración básica del pico
pickaxe:
  display-name: "&f&lPICO &7&l| &a&lINICIAL"
  lore:
    - ""
    - "&fDueño: &f%player%"
    - ""
    - "&a&lEncantamientos:"
    - "&2» {}"

# Encantamientos
enchants:
  speed:
    display: "&7Speed"
    max-level: 2
    enabled: true
  explosive:
    display: "&7Explosive"
    max-level: 50
    enabled: true
  efficiency:
    display: "&7Efficiency"
    max-level: 100
    enabled: true
  fortune:
    display: "&7Fortune"
    max-level: 20
    enabled: true
  fly:
    display: "&7Fly"
    max-level: 1
    enabled: true

# Bloques permitidos
allowed-blocks:
  - STONE
  - COBBLESTONE
  - IRON_ORE
  - GOLD_ORE
  - DIAMOND_ORE
  - DIAMOND_BLOCK
  - EMERALD_BLOCK

fortune-blocks:
  - DIAMOND_BLOCK
  - EMERALD_BLOCK

# Base de datos
database:
  host: localhost
  name: minecraft
  username: usuario
  password: contraseña